export const taskData = [
    {
        id : 1,
        name: "Task 1",
        totalTasks: 10,
        code: "for (let i = 0; i < 10; i++) { console.log(i); }",
        completedTasks: 8,
        attempts: 12,
        errors: 3,
        successRate: 80,
        timeSpent: "5 hours",
        deadlines: ["2024-11-01", "2024-11-02", "2024-11-03"],
        programmingLanguage: "Python"
    },
    {
        id : 2,
        name: "Task 2",
        totalTasks: 15,
        code: "public static void main(String[] args) { System.out.println('Hello'); }",
        completedTasks: 15,
        attempts: 15,
        errors: 0,
        successRate: 100,
        timeSpent: "8 hours",
        deadlines: ["2024-11-04", "2024-11-05", "2024-11-06"],
        programmingLanguage: "Java"
    },
    {
        id : 3,
        name: "Task 3",
        totalTasks: 8,
        code: "<html><body><h1>Hello World</h1></body></html>",
        completedTasks: 6,
        attempts: 9,
        errors: 2,
        successRate: 75,
        timeSpent: "4 hours",
        deadlines: ["2024-11-07", "2024-11-08", "2024-11-09"],
        programmingLanguage: "HTML"
    },
    {
        id : 4,
        name: "Task 4",
        totalTasks: 12,
        code: "SELECT * FROM students WHERE age > 18;",
        completedTasks: 9,
        attempts: 10,
        errors: 1,
        successRate: 90,
        timeSpent: "6 hours",
        deadlines: ["2024-11-10", "2024-11-11", "2024-11-12"],
        programmingLanguage: "SQL"
    },
    {
        id : 5,
        name: "Task 5",
        totalTasks: 6,
        code: "function factorial(n) { return n === 0 ? 1 : n * factorial(n - 1); }",
        completedTasks: 5,
        attempts: 6,
        errors: 1,
        successRate: 83,
        timeSpent: "3 hours",
        deadlines: ["2024-11-13", "2024-11-14", "2024-11-15"],
        programmingLanguage: "JavaScript"
    },
    {
        id : 6,
        name: "Task 6",
        totalTasks: 9,
        code: "const sum = (a, b) => a + b;",
        completedTasks: 8,
        attempts: 8,
        errors: 0,
        successRate: 100,
        timeSpent: "5 hours",
        deadlines: ["2024-11-16", "2024-11-17", "2024-11-18"],
        programmingLanguage: "JavaScript"
    },
    {
        id : 7,
        name: "Task 7",
        totalTasks: 11,
        code: "System.out.println('Task completed');",
        completedTasks: 9,
        attempts: 10,
        errors: 1,
        successRate: 82,
        timeSpent: "7 hours",
        deadlines: ["2024-11-19", "2024-11-20", "2024-11-21"],
        programmingLanguage: "Java"
    },
    {
        id : 8,
        name: "Task 8",
        totalTasks: 7,
        code: "#include <iostream> int main() { std::cout << 'Hello'; return 0; }",
        completedTasks: 5,
        attempts: 7,
        errors: 2,
        successRate: 71,
        timeSpent: "3 hours",
        deadlines: ["2024-11-22", "2024-11-23", "2024-11-24"],
        programmingLanguage: "C++"
    },
    {
        id : 9,
        name: "Task 9",
        totalTasks: 5,
        code: "print('Data analysis complete')",
        completedTasks: 5,
        attempts: 5,
        errors: 0,
        successRate: 100,
        timeSpent: "2 hours",
        deadlines: ["2024-11-25", "2024-11-26", "2024-11-27"],
        programmingLanguage: "Python"
    },
    {
        id: 10,
        name: "Task 10",
        totalTasks: 14,
        code: "echo 'Hello World';",
        completedTasks: 12,
        attempts: 14,
        errors: 2,
        successRate: 86,
        timeSpent: "9 hours",
        deadlines: ["2024-11-28", "2024-11-29", "2024-11-30"],
        programmingLanguage: "PHP"
    }
];
